Added error in StartLiveReload
shift72/kibble pull request #107
Opened 2022-02-17 02:37 UTC by brynyShift72

AB#6791 Kill Render on Error
Needed to stop Error messages from printing to screen and continuing to render the site, will kill the process so developer is forced to face problem

2022-02-17 07:15 UTC, PeculiarGoat approved these changes
LGTM!

2022-02-17 20:19 UTC, smitsanghvi21 approved these changes

2022-03-03 04:02 UTC, l0ud0gg commented
is this only in effect when running sites locally? or is this also run when sites are built on the server?

2022-03-03 04:05 UTC, brynyShift72 commented
> is this only in effect when running sites locally? or is this also run when sites are built on the server?
My understanding this that it will only stop the local version, I don't think LiveReload is called in the building of a site? Would be good to test on staging first. I think anything that errors in LiveReload would cause a errored build anyway

2022-03-03 04:06 UTC, l0ud0gg requested changes
just wanting to understand a bit better before approving. I feel like ive seen this happen on live sites, sometimes when the clients done something that their template doesnt support. i.e. we allow the client to add bundles to the carousel in admin but its on a newer version of kibble / relish / core template. the client has added one and its caused and error in the build. it will add a sneaky error in the html in a div but the site will still work. Is that the case with this? if so maybe taking down a live site due to a render error is overkill and theres a better way to manage it. if its for local dev sites only then i think its all good.

2022-03-03 04:38 UTC, PeculiarGoat commented
@l0ud0gg yeah from what I can tell this error code can only run during `kibble render --watch` which is only used when running the templates locally I believe.  Maybe we could do a test release with just this feature to make sure nothing weird can happen and then delete the release if it's no good?

2022-03-03 21:31 UTC, stajs commented
> maybe taking down a live site due to a render error is overkill

It wouldn't "take it down" per se, but yeah stopping new builds: I'm leaning towards that being a good thing as I think it's worse to have those HTML error divs messing up the design. At least if there is a build error and they raise through support that the site is not updating we can start diagnosing problems sooner rather than later. But that's all moot for now as y'all saying this PR just adds the error the live reload which prod builds aren't going to be hitting (but if we did in the future I'd prob be fine with).

2022-03-03 21:50 UTC, curtisadams28 approved these changes

2022-03-10 00:38 UTC, brynyShift72 commented
@l0ud0gg Happy for merge?

2022-03-10 02:43 UTC, l0ud0gg approved these changes

2022-03-10 02:47 UTC, merged